### PR TITLE
docs: Added pnpm into README.md installs

### PR DESCRIPTION
**Pull request by Kaparrs**
### Before the change?

*  `pnpm` wasn't in the README.md install documentation 

### After the change?

* `pnpm` is in the README.md install documentation 

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x ] No

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by Kaparrs** [comment]
for some odd reason I'm unable to add Labels

**Comment by wolfy1339** [comment]
> for some odd reason I'm unable to add Labels

That is the normal behaviour on GitHub. Only people added to an organization, or as a repository contributor can add labels.

The section in the PR template that asks for a label, you only need to keep the label that applies to the PR

**Comment by Kaparrs** [comment]
Ah, ok!

**Review by nickfloyd — APPROVED** [review]
@JajarGaming Thanks for the contrib here.  ❤️

**Pull request merged**
