### PR TITLE
docs: fix deno import

### PR DESCRIPTION
**Pull request by rojvv**
null

-----
[View rendered README.md](https://github.com/rojserbest/octokit.js/blob/patch-1/README.md)

### CODE REVIEW

**Comment by wolfy1339** [comment]
While you're at it, would you mind changing the other imports as well?

**Comment by rojvv** [comment]
Do you mean removing `Action` from Node.js imports too?

**Comment by wolfy1339** [comment]
> Do you mean removing `Action` from Node.js imports too?

Yup, that's exactly what I mean

**Comment by rojvv** [comment]
Done, I fixed all of them in a commit.

**Review by wolfy1339 — APPROVED** [review]

**Pull request merged**
