### PR TITLE
fix(build): actually output ESM

### LINKED ISSUE #2676: [BUG]: Octokit 4 can't be `import`ed or `require`d
### What happened?

This should work:

`a.mjs`:

```js
import * as octokit from 'octokit'
```

However this fails with a module loading error (see later).

Note that `octokit@4.0.1` ships with `"type": "module"` in its `package.json`, indicating a pure ESM package, but `"main"` points to `dist-node/index.js`, which is clearly a CJS module making use of `module.exports` and `require`. Something's gone wrong here.

### Versions

Octokit 4.0.1, Node.js 18.17.1

### Relevant log output

```shell
C:\...>node a.mjs
file:///C:/.../node_modules/octokit/dist-node/index.js:29
module.exports = __toCommonJS(dist_src_exports);
^

ReferenceError: module is not defined in ES module scope
    at file:///C:/.../node_modules/octokit/dist-node/index.js:29:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.17.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wolfy1339**
Resolves #2676

----

### Before the change?

* The build script still outputted CJS
* Consumers couldn't use the package at all

### After the change?

* The build script is now updated to output ESM

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [ ] No

----

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
Sorry I missed this when I reviewed your v4 PR, I should have properly tested it 😞

**Comment by brent85** [comment]
> Resolves #2676
> 
> ### Before the change?
> * The build script still outputted CJS
> * Consumers couldn't use the package at all
> 
> ### After the change?
> * The build script is now updated to output ESM
> 
> ### Pull request checklist
> * [ ]  Tests for the changes have been added (for bug fixes / features)
> * [ ]  Docs have been reviewed and added / updated if needed (for bug fixes / features)
> 
> ### Does this introduce a breaking change?
> Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
> 
> * [ ]  Yes
> * [ ]  No



> Member

"Docs"

**Comment by brent85** [comment]
> Resolves #2676
> 
> ### Before the change?
> * The build script still outputted CJS
> * Consumers couldn't use the package at all
> 
> ### After the change?
> * The build script is now updated to output ESM
> 
> ### Pull request checklist
> * [ ]  Tests for the changes have been added (for bug fixes / features)
> * [ ]  Docs have been reviewed and added / updated if needed (for bug fixes / features)
> 
> ### Does this introduce a breaking change?
> Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
> 
> * [ ]  Yes
> * [ ]  No



> Member



> Resolves #2676
> 
> ### Before the change?
> * The build script still outputted CJS
> * Consumers couldn't use the package at all
> 
> ### After the change?
> * The build script is now updated to output ESM
> 
> ### Pull request checklist
> * [ ]  Tests for the changes have been added (for bug fixes / features)
> * [ ]  Docs have been reviewed and added / updated if needed (for bug fixes / features)
> 
> ### Does this introduce a breaking change?
> Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
> 
> * [ ]  Yes
> * [ ]  No

https://github.com/octokit/octokit.js/pull/2678#issue-2285628885

**Review by ranajiu7 — COMMENTED** [review]
Good

**Pull request merged**
