### PR TITLE
ci: stop testing against NodeJS v14, v16

### PR DESCRIPTION
**Pull request by wolfy1339**
BREAKING CHANGE: Drop support for NodeJS v14, v16

### CODE REVIEW

**Comment by kfcampbell** [comment]
@wolfy1339 Node 16 is still supported until [September 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol). What's the justification for stripping it before then?

**Comment by wolfy1339** [comment]
It was suggested by @gr2m in https://github.com/octokit/webhooks.js/pull/849#pullrequestreview-1425468491

In order to avoid making another breaking release in a couple months

**Review by kfcampbell — APPROVED** [review]

**Comment by wolfy1339** [comment]
Something is up with branch protection. It currently requires node 10 and 12. which were removed a whiles back

**Comment by gr2m** [comment]
> Something is up with branch protection. It currently requires node 10 and 12. which were removed a whiles back

most likely we didn't update the `beta` branch protections, on it

**Pull request merged**
